---
title: "Composition Analysis"
output: html_notebook
---

What is going on in 2008? Why 

```{r, include = FALSE}
library(dplyr)
library(tidyr)
library(knitr)

# Cover data (wide format)
cover <- read.csv("../data/comdata_wideformat.csv", 
                  header = TRUE, 
                  stringsAsFactors = FALSE)
group_percents = cover[,12:23]
cover = cover[,-(12:23)]
colnames(cover)

# Treatment labels and group structure
trtlabels <- read.csv("../data/trtlabels.csv",
          header = TRUE,
          stringsAsFactors = FALSE)

# Biomass data
biomass <-  read.csv("../data/biomass_all.csv", 
                  header = TRUE, 
                  stringsAsFactors = FALSE)

# Other treatment labels (checking for redundancy)
checklabels <- read.csv("../data/plot_ids.csv",
          header = TRUE,
          stringsAsFactors = FALSE)

checklabels$Sp.comp <- gsub(" ", "", checklabels$Sp.comp)

# Species treatments
waps.specs <- read.csv("../data/WAPSspecies.csv",
                       header = TRUE,
                       stringsAsFactors = FALSE)
```

```{r, size = "tiny"}
relevant_trts = c("annuals", "WAPS", "Natives", "natives+WAPS+annuals", "annuals+natives", "WAPS+annuals", "WAPS+natives")

checklabels = checklabels[checklabels$Sp.comp %in% relevant_trts,]

table(checklabels %>% select(one_of("H2O", "Sp.comp", "Fertilization", "Clipping")))
```

#How many total observations (plot x year) are there for each unique treatment combination in the cover dataset?

```{r}
relevant_trts = c("annuals", "WAPS", "Natives", "natives+WAPS+annuals", "annuals+natives", "WAPS+annuals", "WAPS+natives")

group_percents = group_percents[cover$sp.trt %in% relevant_trts,]
cover = cover[cover$sp.trt %in% relevant_trts,]

cover %>% 
  group_by(sp.trt) %>% 
  filter(h2o != "control-2nd") %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```

# Do cover data labels line up with data checking labels?

```{r}
library(testthat)

for(rowindex in 1:nrow(cover)){
  
  plotno = cover$plot[rowindex]
  
  # Is water the same?
  expect_equivalent(cover$h2o[rowindex], checklabels$H2O[checklabels$Plot.. == plotno])
  
  # Is fertilizer the same?
  expect_equivalent(cover$fertilization[rowindex], checklabels$Fertilization[checklabels$Plot.. == plotno])

  # Is clipping the same?
  expect_equivalent(cover$clip[rowindex], checklabels$Clipping[checklabels$Plot.. == plotno])
  
}

head(cover)
```

# Do group (class) totals equal those supplied on the general data summary? 

```{r}
calc_class_percent <- function(x){
  
  sums = c()
  count = 1
  
  for(g in unique(waps.specs$group)){
    sums[count] = sum(x[,colnames(x) %in% waps.specs$specname[waps.specs$group == g]])
    count = count + 1
  }
  
  names(sums) =  unique(waps.specs$group)
  
  return(data.frame(t(sums)))
}

class_percent <- cover %>% group_by(plot, year, sp.trt) %>% do(calc_class_percent(.))

diff_ann <- c();diff_nat<- c();diff_waps<- c(); diff_weeds<- c()

for(rowindex in 1:nrow(class_percent)){
  
  diff_ann[rowindex] = class_percent$annual[rowindex] - group_percents$annuals[rowindex]
  diff_nat[rowindex] = class_percent$natives[rowindex] - group_percents$natives[rowindex]
  diff_waps[rowindex] = class_percent$waps[rowindex] - group_percents$waps[rowindex]
  diff_weeds[rowindex] = class_percent$weeds[rowindex] - group_percents$weeds[rowindex]

}

group_diffs = data.frame(diff_ann, diff_nat, diff_waps, diff_weeds)

# write.csv("../data/func_group_percents.csv",
#           x = class_percent)
```

```{r, warning=FALSE}
library(ggplot2)

gather(class_percent, key = "class", value = "cover", -c(plot, year, sp.trt)) %>%
  ggplot(aes(x = year,
      y = cover,
      color = class)) +
  facet_wrap(~sp.trt) +
  geom_point(alpha = .01) +
  stat_smooth(method = "loess") +
  ylim(0, 150) +
  ggtitle("Calculated Default Group Cover per Year")
```

```{r, warning=FALSE}
library(ggplot2)

gather(class_percent, key = "class", value = "cover", -c(plot, year, sp.trt)) %>%
  filter(class %in% c("waps", "annual", "natives")) %>%
  ggplot(aes(x = year,
      y = cover,
      color = class)) +
  facet_wrap(~sp.trt) +
  geom_point(alpha = .01) +
  stat_smooth(method = "loess") +
  ylim(0, 150) +
  ggtitle("Calculated Default Group Cover per Year \nControl Treatment")
```